[project]
name = "raqun"
version = "0.1.0"
description = "RAQun is a Python package for comparing ML algorithms"
authors = [
    { name = "Jose Armando Noguez Martinez", email = "armandonoguez113@gmail.com" }
]
readme = "README.md"
requires-python = ">=3.10"

dependencies = [
    "pennylane>=0.44",
    "scikit-learn>=1.8",
    "numpy>=2.4",
    "pennylane-lightning>=0.44",
]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"